## Numpy introduction

In [2]:
# importing linrary
import numpy as np

### What is an array?



An array is a data structure that stores a collection of elements, where each element can be accessed using an index or a key. The elements in an array are typically of the same data type, and they are stored in contiguous memory locations. The index is an integer value that represents the position of an element in the array. Arrays are widely used in programming to organize and manipulate collections of data.




In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [6]:
a2.shape

(1, 6)

In [7]:
a3=a2[np.newaxis, :]
a3.shape

(1, 1, 6)

### Creating arrays with numpy

In [10]:
a= np.array([1, 2, 3, 4, 5, 6])
b= np.array([(4, 5, 6, 7, 8, 9),(10, 11, 12, 13, 14, 15)])

# a.shape
b.shape

(2, 6)

## initialize arrays

In [11]:
zeros=np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
ones= np.ones((4, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
full= np.full((5, 3), 7.6)
full

array([[7.6, 7.6, 7.6],
       [7.6, 7.6, 7.6],
       [7.6, 7.6, 7.6],
       [7.6, 7.6, 7.6],
       [7.6, 7.6, 7.6]])

In [16]:
identity= np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## array attributes

In [17]:
a.shape

(6,)

In [18]:
b.shape

(2, 6)

In [19]:
len(a)

6

In [20]:
a.ndim

1

In [24]:
b.shape # shapes of array

(2, 6)

In [29]:
len(b) # gives length of elements

2

In [26]:
b.ndim # gives number of dimensions

2

In [28]:
b.size # gives total number of elements

12

In [30]:
g= a-b # subracting
g



array([[-3, -3, -3, -3, -3, -3],
       [-9, -9, -9, -9, -9, -9]])

In [31]:
g= a+b # adding 
g

array([[ 5,  7,  9, 11, 13, 15],
       [11, 13, 15, 17, 19, 21]])

In [32]:
# another way of adding
h1= np.add(a, b)
h1

array([[ 5,  7,  9, 11, 13, 15],
       [11, 13, 15, 17, 19, 21]])

In [33]:
# multiplying
h2= np.multiply(a, b)
h2

array([[ 4, 10, 18, 28, 40, 54],
       [10, 22, 36, 52, 70, 90]])

In [34]:
# division
h3= np.divide(a, b)
h3

array([[0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667],
       [0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
        0.4       ]])

In [35]:
# square root
h4= np.sqrt(a)
h4

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])