In [12]:
# importing numpy
import numpy as np

In [13]:
empty = np.empty((2,3))
print(empty)

[[ 0.   3.7  7.4]
 [11.1 14.8 18.5]]


In [14]:
empty = np.empty((2,4))
print(empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [16]:
# even number
even= np.arange(2, 20, 2)
print(even)

[ 2  4  6  8 10 12 14 16 18]


In [17]:
# odd number
odd= np.arange(1, 20, 2)
print(odd)

[ 1  3  5  7  9 11 13 15 17 19]


In [18]:
# difference
diff= np.arange(0, 20, 3.7)
print(diff)

[ 0.   3.7  7.4 11.1 14.8 18.5]


In [19]:
# linspace
lin1=np.linspace(0, -10, num=10)



In [20]:
lin2=np.linspace(0, 10, num=5)
lin2


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
lin1.dtype

dtype('float64')

In [22]:
# define the data type of array
x=np.ones(5, dtype=np.float64)
x

array([1., 1., 1., 1., 1.])

### What is the difference between int 32, 64 in numpy?

=>In NumPy, int32 and int64 refer to different data types representing integers with 32 bits and 64 bits of precision, respectively.

int32 (32-bit integer):

Range: -2,147,483,648 to 2,147,483,647
Memory Usage: 32 bits (4 bytes)
int64 (64-bit integer):

Range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807
Memory Usage: 64 bits (8 bytes)
The key difference lies in the range of values each data type can represent and the amount of memory they occupy. int64 allows for larger integers but consumes more memory compared to int32. The choice between them depends on the specific requirements of your application. If you need to store very large integers or perform operations that might result in overflow with 32-bit integers, you may opt for int64. However, if memory efficiency is a concern and your data fits within the range of a 32-bit integer, you might choose int32 to conserve memory.

In [23]:
# sorting an array
x= np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

### In addition to sort, which returns a sorted copy of an array, we can use:

argsort, which is an indirect sort along a specified axis,

lexsort, which is an indirect stable sort on multiple keys,

searchsorted, which will find elements in a sorted array, and

partition, which is a partial sort.

In [24]:
# concatenate
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [25]:
#concatenate 2d array row wise
x = np.array([[1, 2], [3, 4]]) # 2x2
y = np.array([[5, 6]]) # 1x2

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
len(x)

2

In [27]:
len(y)

1

In [28]:
# concatenate 2d array column wise (2x2 array needed)
x = np.array([[1, 2], [3, 4]]) # 2x2
y = np.array([[5, 6], [7, 8]]) # 1x2

np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## 3D array

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [30]:
array_example.size

24

In [31]:
array_example.dtype

dtype('int32')

In [32]:
array_example.shape

(3, 2, 4)

In [33]:
len(array_example)

3

In [34]:
# create 3D array of size(3,1,4)
x = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]]])

x.ndim

3

In [39]:
# reshape
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [37]:
y=x.reshape(4,3)
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
y.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
# create a 1d array
a=np.array(([1,2,3,4,5,6,7,8]))
a.shape

(8,)

In [44]:
a[np.newaxis, :].shape

#a.reshape(1,8)

(1, 8)

### indexing and slicing

In [45]:
a=np.array(([1,2,3,4,5,6,7,8]))
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
a[2:6]

array([3, 4, 5, 6])

In [47]:
a[1:6:2]

a[0:6:2]

array([1, 3, 5])

In [48]:
a[a<6]

array([1, 2, 3, 4, 5])

In [49]:
a[a%2==0]

array([2, 4, 6, 8])

In [50]:
# using multiple conditions
a[(a>2) & (a<6) & (a%2==0)]

array([4])

### how to create an array from an existing data

In [51]:
a= np.arange(0,222,5)

In [52]:
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [53]:
len(a)

45

In [54]:
array1= a[40:45]
array1

array([200, 205, 210, 215, 220])

In [55]:
a= np.array([1,2,3,4,5,6,7])
b=np.array([1,2,3,4,5,6,7])

c=np.vstack((a,b))
c

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [56]:
d=np.hstack((a,b))
d

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

### Matrix or Matrices

In [58]:
# creating a 2x3 matrix
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
# creating a matrix 
y= np.arange(0,100,2).reshape(5,10)
y

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [69]:
# slicing a matrix
y[1:4,3:5]

array([[26, 28],
       [46, 48],
       [66, 68]])

In [70]:
y.max()

98

In [71]:
y.min()

0

In [72]:
# maximum values only for columns
y.max(axis=0)

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [73]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [74]:
m * np.array([20, 22])

array([[  0,  44],
       [ 80, 132],
       [160, 220],
       [240, 308],
       [320, 396]])

In [75]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [76]:
b

array([1, 2, 3, 4, 5, 6, 7])

In [77]:
np.flip(b)

array([7, 6, 5, 4, 3, 2, 1])